name: Programming Historian
description: Introductory and intermediate programming lessons for humanists
url: http://programminghistorian.github.io/ph-submissions
permalink: :categories/:title
exclude: [deprecated, vendor, Gemfile, Procfile]
safe: true
highlighter: rouge
markdown: kramdown
gems:
  - jekyll-redirect-from

